---
- name: leadup
  hosts: debian

  vars:
    user_name: alex
    gui: yes

  roles:
  - localectl
  - mc
  - htop
  - git
  - ntp
  - ssh
  - vim
  - emacs
  - samba
  - parted
  - kvpm
  - xfce4-terminal
  - nodejs
  - rust
  - unison
  - clementine
  - vlc
  - gimp
  - inkscape
  - flatpak
  - snappy
  - deluge 
  - chromium
  - firefox
  - gramps
  - workrave
  - wine
  - i3


