---
- name: i3
  package: name=i3 state=latest
  ignore_errors: yes

- name: i3 config
  become_user: "{{user_name}}"
  copy: src="{{src}}" dest="{{dst}}"
  ignore_errors: yes

- name: i3lock
  package: name=i3lock state=latest
  ignore_errors: yes
