---
- name: i3
  package: name=i3 state=latest
  ignore_errors: yes

- name: i3lock
  package: name=i3lock state=latest
  ignore_errors: yes

- name: i3 config dir
  become_user: "{{user_name}}"
  file:
    path: ~/.config/i3/
    state: directory
    recurse: yes
  ignore_errors: yes

- name: i3 config
  become_user: "{{user_name}}"
  copy: src=config dest=~/.config/i3/
  ignore_errors: yes
