---
- name: nvm
  become: "{{user_name}}"
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  args: 
    warn: no
  ignore_errors: yes

- name: yarn 
  become: "{{user_name}}"
  shell: curl -o- -L https://yarnpkg.com/install.sh | bash
  args: 
    warn: no
  ignore_errors: yes