---
- name: i3
  apt: name=i3 state=latest
  when: ansible_os_family == "Debian"
  ignore_errors: yes

- name: i3 config dir
  become_user: "{{user_name}}"
  file: 
    path: ~/.config/i3/
    state: directory
    recurse: yes
  ignore_errors: yes

- name: i3 config
  become: yes
  become_user: "{{user_name}}"
  copy: src=config dest=~/.config/i3/
  ignore_errors: yes
