---
- include_role: name=__basic

- include_role: name="groups/{{group_name}}"
  with_items: "{{app_groups}}"
  loop_control:
    loop_var: group_name

  vars:
    app_groups:
    - development
    - development-gui
