---
- name: samba
  package: name=samba state=latest
  ignore_errors: yes

- name: samba client
  ignore_errors: yes
  include_tasks: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}.yml"
  - "default.yml"