---
- name: nvm
  become: true
  become_user: "{{user_name}}"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    warn: no
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"